### PR TITLE
Added netscape.javascript package.

### PR DESCRIPTION
**Pull request by collymy**
If interacting with JavaScript in a WebView one needs netscape.javascript.JSObject and netscape.javascript.JSException, hence it would be useful to export the netscape.javascript package.

### CODE REVIEW

**Comment by edvin** [comment]
Thank you :)

**Comment by collymy** [comment]
Hi.
You are welcome.
Thanks for merging it so quickly.
Colly 

    On Friday, 28 December 2018, 20:51:01 GMT, Edvin Syse <notifications@github.com> wrote:  
 
 
Thank you :)

**Comment by edvin** [comment]
My pleasure. I've also pushed version 8.0.3 to Maven Central now.

**Comment by collymy** [comment]
Hi. That's great. Thanks Colly 

    On Saturday, 29 December 2018, 10:56:17 GMT, Edvin Syse <notifications@github.com> wrote:  
 
 
My pleasure. I've also pushed version 8.0.3 to Maven Central now.

**Pull request merged**
